version: "2.1"
services:
  localstack:
    image: localstack/localstack-full
    ports:
      - "4566:4566"
      - "4569:4569"
      - "4576:4576"
      - "4564:4564"
      - "8080:8080"
    environment:
      - SERVICES=dynamodb
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
