service: lambda-environment

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, "qa"}
  iam:
    role:
      statements: ${file(./config/serverless/db.iam.role.yaml)}
  environment: ${file(./config/env.${self:provider.stage}.json)}

custom:
  schedulerRate: rate(1 minute)
  enabled: true
  tableName: ${self:provider.environment.DbTableName}
  dbWriteCapacityUnits: ${self:provider.environment.DbWriteCapacityUnits}
  dbReadCapacityUnits: ${self:provider.environment.DbReadCapacityUnits}

functions:
  commit-message-scheduler:
    handler: handler.scheduler
    events:
      - schedule:
          rate: ${self:custom.schedulerRate}
          name: scheduler-commit-message-${self:provider.stage}
          description: get commit messages each minute
          enabled: ${self:custom.enabled}

resources:
  Resources: ${file(./config/serverless/resources/dynamo.hero.table.yaml)}
