org: ederfmatos
app: api-management
service: api-management

frameworkVersion: "2"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  apiKeys:
    - free: ${file(./default-customers.js):private}
    - paid:
        - myPaidKey
        - rony@rustico

  usagePlan:
    - free:
        quota:
          limit: 5
          period: MONTH
        throttle:
          burstLimit: 200
          rateLimit: 200
    - paid:
        quota:
          limit: 1000
          period: DAY
        throttle:
          burstLimit: 400
          rateLimit: 50

package:
  excludeDevDependencies: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
          private: true
